"""add preview url column

Revision ID: 4421e863375f
Revises: 2df0ba2991be
Create Date: 2025-05-29 12:40:19.033090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4421e863375f'
down_revision: Union[str, None] = '2df0ba2991be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('preview_url', sa.String(), nullable=True) , schema='file_storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'preview_url', schema='file_storage')
    # ### end Alembic commands ###
